### PR TITLE
fix: make coroutine.addYieldHandler work and wrap tapCatch

### PR DESCRIPTION
**Pull request by mariodu**
After shimCoroutine for Promise.coroutine, the origin method `Promise.coroutine.addYieldHandler` will missing.So, should add origin `Promise.coroutine.addYieldHandler` back to wrapped `Promise.coroutine`. And wrap bluebird v3 method `tapCatch`.

### CODE REVIEW

**Comment by mariodu** [comment]
@TimBeyer

**Comment by overlookmotel** [comment]
@mariodu Thanks for the PR. It would be helpful if you could split this into 2 PRs for the 2 different issues that you're fixing, as they are independent of each other. That will likely get this merged more swiftly.

**Comment by overlookmotel** [comment]
@mariodu Actually, don't bother splitting the PR. I'm implementing both these changes with additional tests and will release soon.

**Comment by overlookmotel** [comment]
Both issues fixed in v2.1.0, just released.

**Comment by mariodu** [comment]
Thanks for fixed it. But, what you done was ...

**Comment by overlookmotel** [comment]
What I done was what?

**Pull request closed without merging**
